name: Génération de PDF avec LaTeX

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_pdf:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le dépôt
      - name: Checkout du code
        uses: actions/checkout@v3

      # Étape 2 : Installer LaTeX
      - name: Installer LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended

      # Étape 3 : Diagnostiquer les fichiers
      - name: Lister les fichiers du répertoire
        run: ls -la

      # Étape 4 : Compiler le fichier LaTeX
      - name: Compiler le fichier LaTeX
        run: |
          mkdir -p output
          pdflatex -interaction=nonstopmode -output-directory=output ./mon_fichier.tex

      # Étape 5 : Ajouter le PDF en tant qu'artifact
      - name: Sauvegarder le PDF généré
        uses: actions/upload-artifact@v3
        with:
          name: fichier-pdf
          path: output/mon_fichier.pdf
